ALTER TABLE "Game" ADD COLUMN "gmEmail" TEXT;
ALTER TABLE "Game" ADD COLUMN "gmReminderSent" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Game" ADD COLUMN "gmDeleteWarned" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Game" ADD COLUMN "baseUrl" TEXT;
