ALTER TABLE "Task" ALTER COLUMN "points" TYPE DOUBLE PRECISION;

ALTER TABLE "Game" ALTER COLUMN "returnPoints" TYPE DOUBLE PRECISION;
ALTER TABLE "Game" ALTER COLUMN "foodDrivePointsPerItem" TYPE DOUBLE PRECISION;

ALTER TABLE "SystemSettings" ALTER COLUMN "returnBonusPoints" TYPE DOUBLE PRECISION;
ALTER TABLE "SystemSettings" ALTER COLUMN "foodDrivePointsPerItem" TYPE DOUBLE PRECISION;
