import { db } from '../db/client';
import { logger } from './logger';

const defaultTasks = [
  {
    title: 'Team Landmark Photo',
    description: 'Take a team photo with a recognizable local landmark in the background.',
    points: 150,
    proofType: 'PHOTO',
    category: 'Team Photo',
    order: 1,
  },
  {
    title: 'Fist Bump a Retiree',
    description: 'Five team members must fist bump a retired public servant or transportation worker.',
    points: 100,
    proofType: 'PHOTO',
    category: 'People',
    order: 2,
  },
  {
    title: 'Civil Servant Handshake',
    description: 'Everyone on your team must shake hands with the same civil servant or community helper.',
    points: 100,
    proofType: 'PHOTO',
    category: 'People',
    order: 3,
  },
  {
    title: 'Then and Now',
    description: "Take a picture of a team member's face next to a physical copy of their baby picture (under one year old).",
    points: 75,
    proofType: 'PHOTO',
    category: 'Memories',
    order: 4,
  },
  {
    title: 'Historical Marker Reading',
    description: 'Three members of your team must read a historical marker aloud, taking turns one word at a time.',
    points: 50,
    proofType: 'VIDEO',
    category: 'History',
    order: 5,
  },
  {
    title: 'Row, Row, Row Your Boat',
    description: 'All team members must touch a boat and sing "Row, Row, Row Your Boat" for at least 32 seconds.',
    points: 100,
    proofType: 'VIDEO',
    category: 'Music',
    order: 6,
  },
  {
    title: 'Silent Store Walk',
    description: 'The entire team must enter a store, walk to the back wall, and exit the front door without speaking.',
    points: 100,
    proofType: 'VIDEO',
    category: 'Pranks',
    order: 7,
  },
  {
    title: 'Story Time for a Dog',
    description: "A member of your team must read two pages of a children's book to a live dog.",
    points: 125,
    proofType: 'VIDEO',
    category: 'Animals',
    order: 8,
  },
  {
    title: 'YMCA with a Stranger',
    description: 'A complete stranger must join four team members in singing the chorus of YMCA with the motions.',
    points: 150,
    proofType: 'VIDEO',
    category: 'Music',
    order: 9,
  },
  {
    title: 'Signed Banana',
    description: 'Have a grocery store clerk sign a banana.',
    points: 100,
    proofType: 'PHOTO',
    category: 'Pranks',
    order: 10,
  },
  {
    title: 'Star Spangled Banner',
    description: 'As a whole team, stand around a flagpole and sing a lesser-known verse of The Star-Spangled Banner.',
    points: 150,
    proofType: 'VIDEO',
    category: 'Music',
    order: 11,
  },
  {
    title: 'Stranger Christmas Carol',
    description: 'Ask a stranger to sing a Christmas carol to your team.',
    points: 150,
    proofType: 'VIDEO',
    category: 'Music',
    order: 12,
  },
  {
    title: 'Hopscotch Course',
    description: 'Using sidewalk chalk, draw a hopscotch course with at least 7 squares; a team member must complete it there and back.',
    points: 50,
    proofType: 'VIDEO',
    category: 'Games',
    order: 13,
  },
  {
    title: 'Other Teams',
    description: "One member must collect a photo of each of the other teams' vehicles or gathering spots.",
    points: 50,
    proofType: 'PHOTO',
    category: 'Vehicles',
    order: 14,
  },
  {
    title: 'Tire Pressure Check',
    description: 'Ask a police officer the tire pressure of their vehicle\'s driver-side rear tire.',
    points: 150,
    proofType: 'PHOTO',
    category: 'Vehicles',
    order: 15,
  },
  {
    title: 'Little Teapot',
    description: 'Seven members must sing "I\'m a Little Teapot" (with motions) along with two firefighters or EMTs.',
    points: 200,
    proofType: 'VIDEO',
    category: 'Music',
    order: 16,
  },
  {
    title: 'High Five Blitz',
    description: 'A member of your team must get 15 high fives from 15 different people in less than 15 seconds.',
    points: 125,
    proofType: 'VIDEO',
    category: 'Games',
    order: 17,
  },
  {
    title: 'Famous Painting Recreation',
    description: 'Physically recreate a famous painting using non-traditional art materials.',
    points: 100,
    proofType: 'PHOTO',
    category: 'Art',
    order: 18,
  },
  {
    title: 'One Sesame Seed',
    description: 'A team member must go into a restaurant and order one single sesame seed.',
    points: 125,
    proofType: 'PHOTO',
    category: 'Pranks',
    order: 19,
  },
  {
    title: 'Group Tree Hug',
    description: 'As a team, group hug a tree.',
    points: 50,
    proofType: 'PHOTO',
    category: 'Nature',
    order: 20,
  },
  {
    title: '1800s Tombstone',
    description: 'Lay a flower on the tombstone of someone born in the 1800s. Respect the site.',
    points: 75,
    proofType: 'PHOTO',
    category: 'History',
    order: 21,
  },
  {
    title: 'Employee Group Photo',
    description: 'Take a group photo with a school or office employee.',
    points: 150,
    proofType: 'PHOTO',
    category: 'Team Photo',
    order: 22,
  },
  {
    title: 'Statue Pose',
    description: 'Your whole team must strike a pose mimicking a statue or monument, and the statue must be in the photo.',
    points: 150,
    proofType: 'PHOTO',
    category: 'Team Photo',
    order: 23,
  },
  {
    title: 'Paint Sample Match',
    description: 'Find a yellow paint sample card and hold it next to a yellow vehicle or object so the card, your face, and the color are all visible.',
    points: 100,
    proofType: 'PHOTO',
    category: 'Art',
    order: 24,
  },
  {
    title: 'Odometer Reading',
    description: 'A team member must read a car\'s mileage aloud while standing next to that physical car.',
    points: 75,
    proofType: 'PHOTO',
    category: 'Vehicles',
    order: 25,
  },
  {
    title: 'Out-of-State Plate',
    description: 'Film a license plate from a state or province other than the one you are playing in.',
    points: 50,
    proofType: 'PHOTO',
    category: 'Vehicles',
    order: 26,
  },
  {
    title: 'Bulk Gerbil Discount',
    description: "At a pet store, ask if they have a bulk discount on gerbils and whether there is much meat on one. You cannot explain until after they answer.",
    points: 175,
    proofType: 'VIDEO',
    category: 'Pranks',
    order: 27,
  },
  {
    title: 'Elbow Portrait',
    description: 'Ask a stranger to take a still picture of a team member\'s left elbow.',
    points: 75,
    proofType: 'PHOTO',
    category: 'Art',
    order: 28,
  },
  {
    title: 'Help Load Groceries',
    description: 'Help a stranger put their groceries into their car.',
    points: 50,
    proofType: 'VIDEO',
    category: 'People',
    order: 29,
  },
  {
    title: 'Headlight Fluid',
    description: 'Go to an auto parts store and ask for a can of "halogen fluid for headlights."',
    points: 175,
    proofType: 'VIDEO',
    category: 'Pranks',
    order: 30,
  },
  {
    title: 'Elmo Interview',
    description: 'In a large store, find an Elmo item. One member interviews Elmo about his early days while another does his voice-over.',
    points: 175,
    proofType: 'VIDEO',
    category: 'Pranks',
    order: 31,
  },
  {
    title: 'Yoda Christmas Carol',
    description: 'Knock on the door of someone not on your team and sing a full verse of a Christmas song in Yoda fashion.',
    points: 200,
    proofType: 'VIDEO',
    category: 'Music',
    order: 32,
  },
  {
    title: 'Shakespeare Sonnet',
    description: 'Find a store clerk willing to recite part of a Shakespearean sonnet with you. Reading from a phone is allowed.',
    points: 150,
    proofType: 'VIDEO',
    category: 'Pranks',
    order: 33,
  },
  {
    title: 'Foreign Phrase',
    description: 'Get a stranger to teach you a phrase in a foreign language. A team member who does not speak the language must repeat it.',
    points: 100,
    proofType: 'VIDEO',
    category: 'People',
    order: 34,
  },
  {
    title: 'Hokey Pokey',
    description: 'Dance the Hokey Pokey in a public place with a bystander. Complete left arm, right arm, left leg, right leg, head, and whole self.',
    points: 125,
    proofType: 'VIDEO',
    category: 'Music',
    order: 35,
  },
  {
    title: 'Staring Contest',
    description: 'Convince a passerby to participate in a staring contest for at least 30 seconds.',
    points: 100,
    proofType: 'VIDEO',
    category: 'Games',
    order: 36,
  },
  {
    title: 'Caricature',
    description: 'Ask a stranger to draw a caricature of you or a team member.',
    points: 100,
    proofType: 'PHOTO',
    category: 'Art',
    order: 37,
  },
  {
    title: 'Human Pyramid',
    description: 'Create a human pyramid with at least one passerby who agrees to join in.',
    points: 150,
    proofType: 'PHOTO',
    category: 'Games',
    order: 38,
  },
  {
    title: 'Simon Says',
    description: 'Get a passerby to play Simon Says led by a team member. At least 3 people including the stranger must play.',
    points: 125,
    proofType: 'VIDEO',
    category: 'Games',
    order: 39,
  },
  {
    title: 'Rock Paper Scissors',
    description: 'Get a stranger to join you in a spontaneous game of rock-paper-scissors.',
    points: 75,
    proofType: 'VIDEO',
    category: 'Games',
    order: 40,
  },
  {
    title: 'Sunglasses Try-On',
    description: 'Approach someone wearing sunglasses and ask if you can try them on to "see the world through their eyes."',
    points: 100,
    proofType: 'PHOTO',
    category: 'Pranks',
    order: 41,
  },
  {
    title: 'Conga Line',
    description: 'Start a conga line with at least three other people in a public area.',
    points: 125,
    proofType: 'VIDEO',
    category: 'Music',
    order: 42,
  },
  {
    title: 'Unique Talent',
    description: 'Find someone with a unique talent and ask them to perform for the team.',
    points: 100,
    proofType: 'VIDEO',
    category: 'People',
    order: 43,
  },
  {
    title: 'Thumb War',
    description: 'Challenge a stranger to a thumb war.',
    points: 75,
    proofType: 'PHOTO',
    category: 'Games',
    order: 44,
  },
  {
    title: 'Park Tag',
    description: 'In a public park, challenge three people not on your team to a game of tag.',
    points: 125,
    proofType: 'VIDEO',
    category: 'Games',
    order: 45,
  },
  {
    title: 'Impromptu Landmark Tour',
    description: 'Locate a local landmark and offer to give a brief impromptu tour to anyone passing by.',
    points: 100,
    proofType: 'VIDEO',
    category: 'History',
    order: 46,
  },
  {
    title: 'Make a Stranger Laugh',
    description: 'Recite a short joke or pun to a stranger and get them to laugh.',
    points: 75,
    proofType: 'VIDEO',
    category: 'People',
    order: 47,
  },
  {
    title: 'Borrowed Phone Call',
    description: 'Convince a stranger to let you borrow their phone to make a quick call, then call your own phone and answer it.',
    points: 175,
    proofType: 'VIDEO',
    category: 'Pranks',
    order: 48,
  },
  {
    title: 'Selfie with Officer',
    description: 'Take a selfie with a police officer or security guard.',
    points: 100,
    proofType: 'PHOTO',
    category: 'People',
    order: 49,
  },
  {
    title: 'Fictional Directions',
    description: 'Approach a stranger with a map and ask for directions to a fictional location, then thank them sincerely.',
    points: 150,
    proofType: 'VIDEO',
    category: 'Pranks',
    order: 50,
  },
  {
    title: 'Hold Up a Building',
    description: 'Discover a street with unique architecture and take a photo of your team pretending to hold up one of the buildings.',
    points: 50,
    proofType: 'PHOTO',
    category: 'Art',
    order: 51,
  },
  {
    title: 'Historical Reenactment',
    description: 'Find a local historical site and take a photo of your team reenacting a part of that history.',
    points: 75,
    proofType: 'PHOTO',
    category: 'History',
    order: 52,
  },
  {
    title: 'Flash Mob',
    description: 'Start a spontaneous flash mob with no music and dance in unison for at least 20 seconds.',
    points: 150,
    proofType: 'VIDEO',
    category: 'Music',
    order: 53,
  },
  {
    title: 'Hot Sauce Shot',
    description: 'Drink a serving of the spiciest hot sauce a nearby restaurant offers.',
    points: 125,
    proofType: 'VIDEO',
    category: 'Games',
    order: 54,
  },
  {
    title: 'Riddle Under a Bridge',
    description: 'Answer a riddle under a bridge. The riddle must be one the team has not heard before; you can look it up.',
    points: 50,
    proofType: 'VIDEO',
    category: 'Games',
    order: 55,
  },
  {
    title: 'Hide and Seek',
    description: 'Play a game of hide-and-seek in a large store.',
    points: 100,
    proofType: 'VIDEO',
    category: 'Games',
    order: 56,
  },
  {
    title: 'Clean Up',
    description: 'Team must collect at least 20 pieces of trash or recycling from a public area and dispose of it properly.',
    points: 50,
    proofType: 'PHOTO',
    category: 'People',
    order: 57,
  },
  {
    title: 'Skip a Stone',
    description: 'Skip a stone at a local lake or pond. The rock must skip at least three times.',
    points: 50,
    proofType: 'VIDEO',
    category: 'Nature',
    order: 58,
  },
  {
    title: 'Befriend a Goose',
    description: 'Talk to a goose and introduce yourself. If it hisses or honks aggressively more than three times, find a new goose.',
    points: 100,
    proofType: 'VIDEO',
    category: 'Animals',
    order: 59,
  },
  {
    title: 'Grocery Obstacle Course',
    description: 'Create an obstacle course in a grocery store aisle, then direct a blindfolded team member through it using only your voice.',
    points: 125,
    proofType: 'VIDEO',
    category: 'Games',
    order: 60,
  },
  {
    title: 'Shoe Circle Catch',
    description: 'Form a circle and toss one team member\'s left shoe around the full circle five times without dropping it.',
    points: 75,
    proofType: 'VIDEO',
    category: 'Games',
    order: 61,
  },
  {
    title: 'Run for Office',
    description: 'Put on a tie and give a speech in front of a government building about becoming mayor while your team hums the national anthem.',
    points: 175,
    proofType: 'VIDEO',
    category: 'Pranks',
    order: 62,
  },
  {
    title: 'Three Animal Friends',
    description: 'Find three different species of living, non-bug, non-bird, non-human animals and capture them clearly on camera.',
    points: 50,
    proofType: 'PHOTO',
    category: 'Animals',
    order: 63,
  },
  {
    title: 'Bird Blitz',
    description: 'Photograph as many different birds as possible in 5 minutes, using only one camera.',
    points: 75,
    proofType: 'PHOTO',
    category: 'Animals',
    order: 64,
  },
  {
    title: 'Coolest Car Team Photo',
    description: 'Take a picture of your whole team with the coolest car you can find.',
    points: 150,
    proofType: 'PHOTO',
    category: 'Team Photo',
    order: 65,
  },
  {
    title: 'Movie Quote Guess',
    description: 'Pick an item at a convenience store and get a stranger to guess it while you describe it using only movie quotes.',
    points: 100,
    proofType: 'VIDEO',
    category: 'Games',
    order: 66,
  },
  {
    title: 'Arm Wrestle a Senior',
    description: 'Arm wrestle someone 70 or older and lose, but put up a valiant effort.',
    points: 100,
    proofType: 'PHOTO',
    category: 'People',
    order: 67,
  },
  {
    title: 'Yodel Echo',
    description: 'One team member must yodel at the base of a water tower while another plays the echo.',
    points: 100,
    proofType: 'VIDEO',
    category: 'Music',
    order: 68,
  },
];

const defaultRules = [
  {
    title: 'HOW TO PLAY',
    body: 'Work together as a team to complete as many challenges as possible before time expires.\n\nEvery completed challenge must include photo or video proof as required by the task.',
  },
  {
    title: 'SCORING',
    body: 'Each task is worth the number of points displayed on the task.',
  },
  {
    title: 'RETURN TIME BONUS',
    body: 'Teams that return to the finish during the return window will receive the return bonus points. The Game Master must confirm your return.',
  },
  {
    title: 'FOOD DRIVE BONUS',
    body: 'Each eligible food drive item turned in is worth points. Permissible and suggested items are listed in the game settings.',
  },
];

export const defaultSystemSettings = {
  foodDriveEnabled: true,
  foodDrivePointsPerItem: 1,
  foodDrivePermissible: 'canned goods, boxed pasta, rice, peanut butter',
  foodDriveSuggested: 'soup, canned vegetables, cereal, diapers',
  returnBonusEnabled: true,
  returnBonusWindowMinutes: 10,
  returnBonusPoints: 100,
  randomizeReturnBonus: false,
  welcomeShown: false,
  tourStep: 0,
  tourDone: false,
  defaultRules: JSON.stringify(defaultRules),
  defaultTasks: JSON.stringify(defaultTasks),
  taskCategories: JSON.stringify([
    'Team Photo',
    'People',
    'Memories',
    'History',
    'Music',
    'Pranks',
    'Animals',
    'Games',
    'Vehicles',
    'Art',
    'Nature',
  ]),
};

export async function seedSystemSettings() {
  try {
    const existing = await db.systemSettings.findFirst();
    if (!existing) {
      await db.systemSettings.create({ data: defaultSystemSettings });
      logger.info('Seeded default system settings');
    }
  } catch (err) {
    logger.error('Could not seed system settings', err);
  }
}

export async function getSystemSettings() {
  let settings = await db.systemSettings.findFirst();
  if (!settings) {
    settings = await db.systemSettings.create({ data: defaultSystemSettings });
  }
  return settings;
}
